// Code generated by `mx build --vercel`. DO NOT EDIT.
package main

import (
	_ "embed"
	"log"
	"net/http"
	"os"

	"github.com/jlkdevelop/mxscript/interpreter"
	"github.com/jlkdevelop/mxscript/lexer"
	"github.com/jlkdevelop/mxscript/parser"
)

//go:embed app.mx
var source string

func main() {
	tokens, err := lexer.New(source).Tokenize()
	if err != nil {
		log.Fatalf("mx lex: %v", err)
	}
	prog, err := parser.New(tokens).Parse()
	if err != nil {
		log.Fatalf("mx parse: %v", err)
	}

	interp := interpreter.New()
	interp.SetFile("app.mx")
	if err := interp.Load(prog); err != nil {
		log.Fatalf("mx load: %v", err)
	}

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	addr := ":" + port
	log.Printf("MX Script (vercel) listening on %s", addr)
	if err := http.ListenAndServe(addr, interp.Handler()); err != nil {
		log.Fatal(err)
	}
}
